OOP school library: unit tests
Elhambasir/add-person-student-and-teacher-classes pull request #8
Opened 2023-07-07 10:29 UTC by Elhambasir

### What is done in this PR?
In this project, I added unit tests to the codebase, specifically to the classes.
- [x] Added unit tests for all the methods in all the classes:

- `Book`
- `Person`
- `Student`
- `Teacher`
- `Classroom`
- `Rental`

[PROJECT REQUIREMENTS](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_unit_tests.md)

Thank you for reviewing :)

2023-07-07 12:24 UTC, franclobo reviewed
Hi @Elhambasir and @LDouglasOT, 

# Invalid Code Review Request

![descarga](https://github.com/Elhambasir/add-person-student-and-teacher-classes/assets/58642949/97c6508e-0cc0-412f-8502-3e85a4c7d9b8)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors ❌ 

```ruby
An error occurred while loading ./spec/classroom_spec.rb. - Did you mean?
                    rspec ./spec/decorator_spec.rb

Failure/Error: require_relative '../classroom'

LoadError:
  cannot load such file -- /home/runner/work/add-person-student-and-teacher-classes/add-person-student-and-teacher-classes/Person
# ./student.rb:1:in `require_relative'
# ./student.rb:1:in `<top (required)>'
# ./classroom.rb:1:in `require_relative'
# ./classroom.rb:1:in `<top (required)>'
# ./spec/classroom_spec.rb:1:in `require_relative'
# ./spec/classroom_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/student_spec.rb. - Did you mean?
                    rspec ./spec/rental_spec.rb

Failure/Error: require_relative '../student'

LoadError:
  cannot load such file -- /home/runner/work/add-person-student-and-teacher-classes/add-person-student-and-teacher-classes/Person
# ./student.rb:1:in `require_relative'
# ./student.rb:1:in `<top (required)>'
# ./spec/student_spec.rb:1:in `require_relative'
# ./spec/student_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/teacher_spec.rb. - Did you mean?
                    rspec ./spec/rental_spec.rb

Failure/Error: require_relative '../teacher'

LoadError:
  cannot load such file -- /home/runner/work/add-person-student-and-teacher-classes/add-person-student-and-teacher-classes/Person
# ./teacher.rb:1:in `require_relative'
# ./teacher.rb:1:in `<top (required)>'
# ./spec/teacher_spec.rb:1:in `require_relative'
# ./spec/teacher_spec.rb:1:in `<top (required)>'

Finished in 0.00004 seconds (files took 0.205[8](https://github.com/Elhambasir/add-person-student-and-teacher-classes/actions/runs/5485631298/jobs/9994673998?pr=8#step:5:9)8 seconds to load)
0 examples, 0 failures, 3 errors occurred outside of examples

Error: Process completed with exit code 1.
```

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-07 14:02 UTC, danmainah requested changes
Hi @Elhambasir and @LDouglasOT , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Ensured all tests added are passing.
✔️ Professional written README file with all sections required.


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-07-07 14:02 UTC, danmainah commented on spec/book_spec.rb
> +  end
- [x] @Elhambasir  and @LDouglasOT Great work adding tests for your book class however you forgot to add tests for the `add_rental` method.

2023-07-07 14:02 UTC, danmainah commented on spec/student_spec.rb
> +  end
- [x] @team Great work adding tests for the student class, however, you forgot to add tests for the method `play_hooky`.

2023-07-07 14:02 UTC, danmainah commented on spec/classroom_spec.rb
> +  end
- [x] @team Great work adding tests for the classroom class, however, you forgot to add tests for the `add_student` method,kindly consider adding tests for it.

2023-07-08 03:19 UTC, Elhambasir commented
Ok thank you

2023-07-08 03:34 UTC, OLIPLICHE approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Added unit tests (✅)) 👏
- All test has passed👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 03:49 UTC, merged